
//for user login
const USER_LOG_IN_REQUEST = 'USER_LOG_IN_REQUEST'
const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_REQUEST'
const USER_LOG_IN_FAILED = 'USER_LOG_IN_REQUEST'

//for search users
const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST'
const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS'
const USER_SEARCH_FAILED = 'USER_SEARCH_FAILED'

//for user inspect searched user
const USER_INSPECT_REQUEST = 'USER_INSPECT_REQUEST'
const USER_INSPECT_SUCCESS = 'USER_INSPECT_SUCCESS'
const USER_INSPECT_FAILED = 'USER_INSPECT_FAILED'
